### ISSUE TITLE
Error when installing react-native-expo-fancy-alerts

### ISSUE THREAD

**Issue by GoDeeper96** [mrnkr/react-native-expo-fancy-alerts#5]
Trying to install the module and get following error

`D:\Projects of Now\anotherone>expo install react-native-expo-fancy-alerts
Installing 1 other package using npm.
> npm install --save react-native-expo-fancy-alerts
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: anotherone@1.0.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.13.1" from react-native-expo-fancy-alerts@2.1.0
npm ERR! node_modules/react-native-expo-fancy-alerts
npm ERR!   react-native-expo-fancy-alerts@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\antid\AppData\Local\npm-cache\eresolve-report.txt for a full report.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\antid\AppData\Local\npm-cache\_logs\2022-05-18T22_44_01_324Z-debug-0.log
npm exited with non-zero code: 1
Error: npm exited with non-zero code: 1
    at ChildProcess.completionListener (C:\Users\antid\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\spawn-async\src\spawnAsync.ts:65:13)
    at Object.onceWrapper (node:events:642:26)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess.cp.emit (C:\Users\antid\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
    ...
    at spawnAsync (C:\Users\antid\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\spawn-async\src\spawnAsync.ts:26:19)
    at NpmPackageManager._runAsync (C:\Users\antid\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\package-manager\src\NodePackageManagers.ts:179:31)
    at NpmPackageManager.addWithParametersAsync (C:\Users\antid\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\package-manager\src\NodePackageManagers.ts:112:18)
    at actionAsync (C:\Users\antid\AppData\Roaming\npm\node_modules\expo-cli\src\commands\installAsync.ts:141:24)`

Expo 45.0.2
Node LTS 16.15.0
Npm 8.5.5
Windows 10.0 19.0.0.5

**Comment by mrnkr** [comment]
So sorry to get back to you this late, I'm not checking this repo often...

I just made a new release bumping up peer dependencies to their latest versions, if you're still using the library feel free to try again.
